### PR TITLE
fix: Able to add fields in invoices without item name idurar#207

### PR DESCRIPTION
**Pull request by 18feb06**
## Description

1. Added a pattern in rules attribute of <Form.Item> component which contain  "Item Name" input (file address : 
    frontend/src/modules/ErpPanelModule/ItemRow.jsx).
2. This pattern contains regular expression which validate that "Item Name must contain alphanumeric or special characters" in 
    real time.

## Related Issues

Able to add fields in invoices without item name https://github.com/idurar/erp-crm/issues/207

## Steps to Test

Create or edit invoice and while adding items in invoice, you can check it.

## Screenshots (if applicable)

https://ibb.co/mzM9sM7

## Checklist

- [ x ] I have tested these changes
- [ x ] I have updated the relevant documentation
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the codebase
- [ x ] My changes generate no new warnings or errors
- [ x ] The title of my pull request is clear and descriptive

### CODE REVIEW

**Comment by polymahh** [comment]
@18feb06 thank you but i think this is already fixed

image

**Comment by 18feb06** [comment]
@polymahh No its not fixed because it is giving error only when its blank, but it should also give error "Item Name must contain alphanumeric or special characters" so that no one will be able to add item with name contaning only spaces or white spaces. You can try demo.

**Review by polymahh — APPROVED** [review]
sorry @18feb06 i didnt understand the issue at first 
tested it's working 👍

**Comment by 18feb06** [comment]
@polymahh Thanks alot.

**Comment by 18feb06** [comment]
@polymahh  Should I close this or you will close this? I don't know because I am new to open source.

**Comment by polymahh** [comment]
@18feb06 no dont close it , i approved it now it needs another approval so it can be merged to dev branch
also always name your branch something descriptive this will be master which is not helpful 
but we can accept since it is one file 
and with every issue created a new branch based on dev , always start from dev
refer to guides in the readme to learn more on open source

**Comment by 18feb06** [comment]
@polymahh thanks for telling and guiding me

**Review by salahlalami — APPROVED** [review]

**Pull request merged**
