### PR TITLE
Pagination limit fix#446

### PR DESCRIPTION
**Pull request by OvilashMoitra**
https://www.loom.com/share/96c6f6e6ca0643aaa0fb4cd8fb46c1e4?sid=2ff5910d-40e9-4928-83c0-948eaa58c132
image
image

### CODE REVIEW

**Comment by OvilashMoitra** [comment]
@polymahh can you check it

**Comment by salahlalami** [comment]
@OvilashMoitra please update and pull from dev branch , we refactor our code

**Comment by OvilashMoitra** [comment]
@salahlalami can you check now.I have updated it.

**Comment by OvilashMoitra** [comment]
@polymahh when I am pulling the code it is saying already up to date and the number of commit with the dev branch matched.Can you please tell me where the problem is?

**Comment by polymahh** [comment]
these files no longer exist in dev branch , do you want to add them ? 
image

**Review by polymahh — CHANGES_REQUESTED** [review]
any update on this ?

**Comment by OvilashMoitra** [comment]
@polymahh thank you. with your help  i have fixed this issue and sorry for being late.I was busy with my semester final exam.I will update the code by today.

**Comment by polymahh** [comment]
hello @OvilashMoitra i tested you code it is working 
can you add it for crud/actions and components/DataTable 
so this solution can work costumers and employee tables

**Comment by OvilashMoitra** [comment]
@polymahh year sure on it.

**Review by polymahh — CHANGES_REQUESTED** [review]
it maybe working for payment invoice correctly because there is a lot of items 
but for invoices it creates empty pages 
image

**Comment by OvilashMoitra** [comment]
@polymahh 
image
Now it will work. showSizeChanger: false was false in the redux action. I removed it.

**Review by polymahh — APPROVED** [review]
tested , LGTM 👍

**Comment by OvilashMoitra** [comment]
@salahlalami can you review this.

**Review by salahlalami — APPROVED** [review]

**Pull request merged**
