### PR TITLE
Features/#314 cache in the frontend

### PR DESCRIPTION
**Pull request by Sinharitik589**
## Description
This pull request introduces caching to the frontend by using the library [React Query](https://tanstack.com/) .The data fetching logic was tied to useFetch custom hook previously but it was not optimised to cache the data . So the proposed caching feature will solve multiple challanges .

1. Caching of the request , which will result in less amount of request sent to backend and thus minimising its load .
2. Managing server side state is now easy.
3. removing the need of multiple requests for same set of data for e.g we are fetching the list of invoices in dashboard , and also in invoices page again 

This pull request introduces some changes in how we fetch server side data and render it , previously we used list item selector
https://github.com/idurar/erp-crm/blob/f2015803acf09c8167389d2715a4d86d97429385/frontend/src/modules/ErpPanelModule/DataTable.jsx#L46

Now we dont need to use redux store for fetching lists because useQuery hook automatically updates data whenever it is invalidated .

Also whenever mutation happens on the server side like create , update and delete , we call the invalidate query function and pass the key invalidating it .

## Related Issues

#314 

## Checklist

- [x] I have tested these changes
- [] I have updated the relevant documentation
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the codebase
- [x] My changes generate no new warnings or errors
- [x] The title of my pull request is clear and descriptive

### CODE REVIEW

**Comment by parteekcoder** [comment]
@Sinharitik589 can you please resolve the merge conflicts

**Comment by Sinharitik589** [comment]
> @Sinharitik589 can you please resolve the merge conflicts

Done

**Comment by salahlalami** [comment]
Thank you @Sinharitik589 , we don't want to add cache to frontend at this stage of development ,
also we want to keep our app clean, and we focus on building more new features instead of rewrite something that it already work.

**Comment by Sinharitik589** [comment]
> Thank you @Sinharitik589 , we don't want to add cache to frontend at this stage of development , also we want to keep our app clean, and we focus on building more new features instead of rewrite something that it already work.

Thanks for considering my pull request , started working on it as it was requested earlier by some of the contributers , is there any platform other than this like discord or slack where features can be discussed more easily , as i wanted to get involve in this project as a contributor.

**Comment by salahlalami** [comment]
@Sinharitik589 check your linkedin message

**Pull request closed without merging**
